### ISSUE TITLE
Error en el pluging ArxiuDigitalCAIBDocumentCustodyPlugin

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/pluginsib-documentcustody#13]
Enviat per @earrivi-fundaciobit :

Os pongo la información por si podemos solucionarlo.

java.lang.NullPointerException
        at org.fundaciobit.plugins.documentcustody.arxiudigitalcaib.ArxiuDigitalCAIBDocumentCustodyPlugin.getOnlyOneMetadata(ArxiuDigitalCAIBDocumentCustodyPlugin.java:1902)
        at es.caib.regweb3.persistence.ejb.AnexoBean.cargarMetadatasAnexo(AnexoBean.java:1683)
        at es.caib.regweb3.persistence.ejb.AnexoBean.getAnexoFullLigero(AnexoBean.java:142)
        at sun.reflect.GeneratedMethodAccessor2307.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.aop.joinpoint.MethodInvocation.invokeTarget(MethodInvocation.java:122)
        at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:111)
        at

En Regweb3 lo que está intentado  hacer es obtener el meadato eni:description:

Metadata metadataDescripcion = custody.getOnlyOneMetadata(anexoFull.getAnexo().getCustodiaID(), MetadataConstants.ENI_DESCRIPCION);

Y en el plugin da un NullPointerException en este método:

@Override
  public Metadata getOnlyOneMetadata(String custodyID, String key) throws CustodyException,
      NotSupportedCustodyException {
    List<Metadata> list = getMetadata(custodyID, key);
    if (list.size() != 0) {
      return list.get(0);
    } else {
      return null;
    }
  }

Parece que el justificante no tiene ese metadato y falla.

**Comment by anadal-fundaciobit** [comment]
Solucionat.
