### ISSUE TITLE
Error el la lectura de Dades Serialitzades a causa del canvi de package de pluginsib-core

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/pluginsib-documentcustody#15]
Error el la lectura de Dades Serialitzades a causa del canvi de package de org.fundaciobit.pluginsib.core.utils a org.fundaciobit.pluginsib.core.v3.utils :

 024-09-04 08:07:26,397 ERROR [es.caib.regweb3.persistence.ejb.AnexoBean] (RegWeb3ThreadPoolTaskScheduler2) class org.fundaciobit.pluginsib.core.utils.Metadata cannot be cast to class org.fundaciobit.pluginsib.core.v3.utils.Metadata (org.fundaciobit.pluginsib.core.utils.Metadata and org.fundaciobit.pluginsib.core.v3.utils.Metadata are in unnamed module of loader 'deployment.regweb3.ear' @46820ec1): java.lang.ClassCastException: class org.fundaciobit.pluginsib.core.utils.Metadata cannot be cast to class org.fundaciobit.pluginsib.core.v3.utils.Metadata (org.fundaciobit.pluginsib.core.utils.Metadata and org.fundaciobit.pluginsib.core.v3.utils.Metadata are in unnamed module of loader 'deployment.regweb3.ear' @46820ec1)
      at deployment.regweb3.ear//org.fundaciobit.pluginsib.documentcustody.api.AbstractDocumentCustodyPlugin.getOnlyOneMetadata(AbstractDocumentCustodyPlugin.java:1225)
      at deployment.regweb3.ear.regweb3-persistence.jar//es.caib.regweb3.persistence.ejb.AnexoBean.cargarMetadatosAnexo(AnexoBean.java:1735)
      at deployment.regweb3.ear.regweb3-persistence.jar//es.caib.regweb3.persistence.ejb.AnexoBean.getAnexoFull(AnexoBean.java:142)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
      at org.jboss.as.ee@7.2.0.GA-redhat-00005//org.jboss.as.ee.component.Manage

**Comment by anadal-fundaciobit** [comment]
Solucionat !!

**Comment by anadal-fundaciobit** [comment]
Solucionats warnings que no afectaven a l'execució:

 09:12:16,478 ERROR [stderr] (default task-1) java.lang.NoSuchMethodException: <unbound>=Metadata.setMetadataType(MetadataType);
09:12:16,479 ERROR [stderr] (default task-1) Continuing ...
09:12:16,481 ERROR [stderr] (default task-1) java.lang.NoSuchMethodException: <unbound>=Metadata.setMetadataType(MetadataType);
09:12:16,482 ERROR [stderr] (default task-1) Continuing ...
09:12:16,490 ERROR [stderr] (default task-1) java.lang.NoSuchMethodException: <unbound>=Metadata.setMetadataType(MetadataType);
09:12:16,492 ERROR [stderr] (default task-1) Continuing ...
09:12:16,495 ERROR [stderr] (default task-1) java.lang.NoSuchMethodException: <unbound>=Metadata.setMetadataType(MetadataType);
09:12:16,496 ERROR [stderr] (default task-1) Continuing ...
09:12:16,497 ERROR [stderr] (default task-1) java.lang.NoSuchMethodException: <unbound>=Metadata.setMetadataType(MetadataType);
09:12:16,498 ERROR [stderr] (default task-1) Continuing ...
09:12:16,499 ERROR [stderr] (default task-1) java.lang.NoSuchMethodException: <unbound>=Metadata.setMetadataType(MetadataType);
09:12:16,500 ERROR [stderr] (default task-1) Continuing ...
09:12:16,501 ERROR [stderr] (default task-1) java.lang.NoSuchMethodException: <unbound>=Metadata.setMetadataType(MetadataType);
09:12:16,505 ERROR [stderr] (default task-1) Continuing ...
09:12:16,506 ERROR [stderr] (default task-1) java.lang.NoSuchMethodException: <unbound>=Metadata.setMetadataType(MetadataType);
09:12:16,507 ERROR [stderr] (default task-1) Continuing ...

**Comment by anadal-fundaciobit** [comment]
Solucionat !!!! Ara si !!!
